import Head from "next/head";
import { Inter } from "@next/font/google";
import { Button } from "ui";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Admin</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="">
          <p className="text-4xl font-bold text-primary">Admin</p>
          <Button />
        </div>
      </main>
    </>
  );
}
