on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

name: 🚀 Deploy website on push

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2

      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: 🔨 Build Project
        run: |
          npm install
          npm run build --filter=main
      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.1.0
        with:
          server: ${{secrets.SERVER}}
          username: ${{secrets.USERNAME}}
          password: ${{secrets.PASSWORD}}
          # dangerous-clean-slate: true
          local-dir: ./apps/main/out/
